# Generated by Django 4.0 on 2022-04-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Tuition_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_end_year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_start_year',
        ),
        migrations.CreateModel(
            name='Tuitions_and_staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staffs')),
                ('tution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuitions')),
            ],
        ),
        migrations.CreateModel(
            name='students_and_tuitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
                ('tuitions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuitions')),
            ],
        ),
        migrations.CreateModel(
            name='Parents_and_wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parents')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
    ]
