# Generated by Django 4.0 on 2022-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staffs_name_staffs_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
