# Generated by Django 4.0 on 2022-04-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Status',
        ),
    ]
