# Generated by Django 4.0 on 2022-04-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
                ('tuition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuitions')),
            ],
        ),
        migrations.CreateModel(
            name='marks_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('marks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.students')),
            ],
        ),
    ]
