# Generated by Django 4.0 on 2022-04-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_attendancereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
