# Generated by Django 4.0 on 2022-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attendance_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
